# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: 'Build and deploy Python app to Azure Web App: flaskWebAppTest2024'

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    
    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.9'
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 'flaskWebAppTest2024'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6e5dbfcf4c0145bb8aadcdd038dc2837 }}

  test:
    needs: build-and-deploy

    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout automation test repo
      uses: actions/checkout@v4
      with:
        repository: hungduonglevel11/TestInGitHubRunners
        path: TestInGitHubRunners

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30